# Generated by Django 4.2 on 2024-09-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('modelo', models.CharField(max_length=40)),
                ('tipo', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=40)),
                ('precio', models.IntegerField(max_length=40)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('modelo', models.CharField(max_length=40)),
                ('tipo', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=40)),
                ('precio', models.IntegerField(max_length=40)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('modelo', models.CharField(max_length=40)),
                ('tipo', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=40)),
                ('precio', models.IntegerField(max_length=40)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Portapuas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('modelo', models.CharField(max_length=40)),
                ('tipo', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=40)),
                ('precio', models.IntegerField(max_length=40)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Entrega',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
