# Generated by Django 4.2 on 2024-09-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0002_amp_instrumento_pedal_portapuas_delete_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amp',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pedal',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='portapuas',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
